--A) Realizar una vista que permita conocer los datos de los usuarios y sus respectivas tarjetas. La misma debe contener: Apellido y nombre del usuario, número de tarjeta SUBE, estado de la tarjeta y saldo.

CREATE VIEW PUNTO_A AS 
	SELECT U.APELLIDOS, U.NOMBRES, T.NROTARJETA, T.SALDO, T.ESTADO FROM USUARIOS U 
	INNER JOIN TARJETAS T ON U.IDUSUARIO = T.IDUSUARIO
	GROUP BY U.APELLIDOS, U.NOMBRES, T.NROTARJETA, T.SALDO, T.ESTADO

SELECT * FROM PUNTO_A

--B) Realizar una vista que permita conocer los datos de los usuarios y sus respectivos viajes. La misma debe contener: Apellido y nombre del usuario, número de tarjeta SUBE, fecha del viaje, importe del viaje, número de interno y nombre de la línea.
CREATE VIEW PUNTO_B AS
	SELECT U.APELLIDOS, U.NOMBRES, T.NROTARJETA, V.COSTO, V.INTERNO, LC.NOMBRE FROM USUARIOS U 
	INNER JOIN TARJETAS T ON T.IDUSUARIO = U.IDUSUARIO
	INNER JOIN VIAJES V ON V.IDTARJETA = T.IDTARJETA
	INNER JOIN LINEAS_COLECTIVOS LC ON V.IDLINEA = LC.IDLINEA
	GROUP BY U.APELLIDOS, U.NOMBRES, T.NROTARJETA, V.COSTO, V.INTERNO, LC.NOMBRE

ALTER VIEW PUNTO_B AS
	SELECT U.APELLIDOS, U.NOMBRES, T.NROTARJETA, V.COSTO, V.INTERNO, LC.NOMBRE FROM USUARIOS U 
	INNER JOIN TARJETAS T ON T.IDUSUARIO = U.IDUSUARIO
	INNER JOIN VIAJES V ON V.IDTARJETA = T.IDTARJETA
	INNER JOIN LINEAS_COLECTIVOS LC ON V.IDLINEA = LC.IDLINEA

--C) Realizar una vista que permita conocer los datos estadísticos de cada tarjeta. La misma debe contener: Apellido y nombre del usuario, número de tarjeta SUBE, cantidad de viajes realizados, total de dinero acreditado (históricamente), cantidad de recargas, importe de recarga promedio (en pesos), estado de la tarjeta.

CREATE VIEW PUNTO_C AS
SELECT 
	US.APELLIDOS, US.NOMBRES,
	(
		SELECT COUNT (*) FROM VIAJES V 
		INNER JOIN TARJETAS T ON V.IDTARJETA = T.IDTARJETA
		WHERE T.IDUSUARIO = US.IDUSUARIO
	)AS CANTIDAD_VIAJES,
	(
		SELECT SUM(M.IMPORTE) FROM MOVIMIENTOS M
		INNER JOIN TARJETAS T ON M.IDTARJETA = T.IDTARJETA
		INNER JOIN TIPO_MOVIMIENTO TP ON M.TIPO = TP.ID
		WHERE T.IDUSUARIO = US.IDUSUARIO AND TP.NOMBRE LIKE 'C' --C CREDITO 
	)AS IMPORTE_ACREDITADO,
	(
		SELECT COUNT(*) FROM MOVIMIENTOS M 
		INNER JOIN TARJETAS T ON M.IDTARJETA = T.IDTARJETA
		INNER JOIN TIPO_MOVIMIENTO TP ON M.TIPO = TP.ID
		WHERE T.IDUSUARIO = US.IDUSUARIO AND TP.NOMBRE LIKE 'C' -- C CREDITO
	)AS CANTIDAD_RECARGAS,
	(
		SELECT AVG(M.IMPORTE) FROM MOVIMIENTOS M 
		INNER JOIN TARJETAS T ON M.IDTARJETA = T.IDTARJETA
		INNER JOIN TIPO_MOVIMIENTO TP ON M.TIPO = TP.ID
		WHERE T.IDUSUARIO = US.IDUSUARIO AND TP.NOMBRE LIKE 'C' -- C CREDITO
	)AS IMPORTE_PROMEDIO,
	T.ESTADO
FROM USUARIOS US
INNER JOIN TARJETAS T ON T.IDUSUARIO = US.IDUSUARIO