CREATE DATABASE Actividad_3_1
GO
USE Actividad_3_1

CREATE TABLE USUARIOS(
	IDUSUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	APELLIDOS VARCHAR(255) NOT NULL,
	NOMBRES VARCHAR(255),
	FNAC DATE NOT NULL,
	DOMICILIO VARCHAR(255) NOT NULL,
	DNI INT NOT NULL UNIQUE,
	ESTADO BIT NOT NULL
)

CREATE TABLE TARJETAS(
	IDTARJETA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NROTARJETA INT NOT NULL UNIQUE, 
	IDUSUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(IDUSUARIO),
	FECHA_ALTA DATE NOT NULL,
	SALDO MONEY NOT NULL,
	ESTADO BIT NOT NULL
)

CREATE TABLE LINEAS_COLECTIVOS(
	IDLINEA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(255) NOT NULL,
	DOMICILIO VARCHAR(255) NOT NULL,
	ESTADO BIT NOT NULL
)

CREATE TABLE VIAJES(
	IDVIAJE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDTARJETA INT NOT NULL FOREIGN KEY REFERENCES TARJETAS(IDTARJETA),
	FECHA DATE NOT NULL,
	COSTO MONEY NOT NULL,
	INTERNO INT NOT NULL,
	IDLINEA INT NOT NULL FOREIGN KEY REFERENCES LINEAS_COLECTIVOS(IDLINEA),
	ESTADO BIT NOT NULL
)

CREATE TABLE TIPO_MOVIMIENTO(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(255) NOT NULL,
	ESTADO BIT NOT NULL
)

CREATE TABLE MOVIMIENTOS(
	IDMOVIMIENTO INT NOT NULL IDENTITY(1,1),
	IDTARJETA INT NOT NULL FOREIGN KEY REFERENCES TARJETAS(IDTARJETA),
	TIPO INT NOT NULL FOREIGN KEY REFERENCES TIPO_MOVIMIENTO(ID),
	FECHA_HORA DATE NOT NULL,
	IMPORTE MONEY NOT NULL,
	ESTADO BIT NOT NULL
)

